name: Sha256sums get and upload
on : workflow_dispatch

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Curl-1
        run: |
          cat payload.json
          curl \
            --header "Authorization:Bearer ${{ secrets.TOKEN }}" \
            --header "Content-Type:application/vnd.api+json" \
            --request POST \
            --data @payload.json \
            https://app.terraform.io/api/v2/organizations/Test-nyx/registry-providers/private/Test-nyx/nyxx/versions


