name: "Fetch release asset"
on: workflow_dispatch

jobs:
  asset_fetcher:
    runs-on: ubuntu-latest
    steps:
    - uses: robinraju/release-downloader@v1.7
      with:
        latest: true
        fileName: "*"
    - run: |
        ls ${{ github.workspace }}
        cat scaffolding_2.0.0_SHA256SUMS.sig

        
