name: Get Version

on: workflow_dispatch

  
jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Fetch latest release version
        run: |
          git fetch --tags
          git fetch --prune --unshallow || true
          export LATEST_RELEASE_VERSION=$(git describe --abbrev=0 --tags)
          echo "::set-output name=latest-release::$(echo $LATEST_RELEASE_VERSION)"
          echo The latest release version is \"$LATEST_RELEASE_VERSION\".



