name: Release

on: workflow_dispatch

jobs:
  Release:

    runs-on: ubuntu-latest

    steps:
    - id: get_version
      name: Get version
      uses: jannemattila/get-version-from-tag@v1

    - name: Display version
      run: |
        VERSION=$(echo "${{ steps.get_version.outputs.version }}")
        echo $VERSION
