name: sha256sums upload link
on: workflow_dispatch
jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: Get nyx release version
        uses: rez0n/actions-github-release@main
        id: nyx
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "hasan-razibul/scaffolding"
          type: "stable"
      - name: echo release number   
        run : echo "${{ steps.nyx.outputs.release }}" | awk 'sub(/^.{1}/,"")' > version.txt

      - name: set output
        id: vars
        run: echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: echo version
        run : echo ${{ steps.vars.outputs.version }}
        
        
        
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Update payload.json version
        uses: chromee/dot-json-edit-action@v1
        with:
          json_path: ".github/workflows/payload.json"
          field_path: "data/attributes/version"
          field_value: "${{ steps.vars.outputs.version }}"
      - name: after edit
        run: cat .github/workflows/payload.json
        
          
      - name: Curl-1
        run: |
          curl \
            --header "Authorization: Bearer ${{ secrets.TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --request POST \
            --data '{
                      "data": {
                        "type": "registry-provider-versions",
                        "attributes": {
                          "version": "${{ steps.vars.outputs.version }}",
                          "key-id": "${{ secrets.KEY_ID }}",
                          "protocols": [
                            "5.0"
                          ]
                        }
                      }
                    }' \
            https://app.terraform.io/api/v2/organizations/Test-nyx/registry-providers/private/Test-nyx/nyxx/versions > provider_version_endpoint.json
      - name: show provider_version_endpoint file   
        run: cat provider_version_endpoint.json
        
      - name: extract shasums-upload link
        run : |
          jq -r .data.links'."shasums-upload"' provider_version_endpoint.json > shasums-upload.txt
          jq -r .data.links'."shasums-sig-upload"' provider_version_endpoint.json > shasums-sig-upload.txt
      - name: show upload links
        run: |
          cat shasums-upload.txt
          cat shasums-sig-upload.txt
      
      - uses: robinraju/release-downloader@v1.7
        with:
          latest: true
          fileName: "*"
      - run: |
          ls ${{ github.workspace }}
      
      - name : open sha256sums
        run: cat scaffolding_${{ steps.vars.outputs.version }}_SHA256SUMS
        
      - name: upload sha256sums files
        run : |
          curl -T scaffolding_${{ steps.vars.outputs.version }}_SHA256SUMS --url "$(cat shasums-upload.txt)"
          curl -T scaffolding_${{ steps.vars.outputs.version }}_SHA256SUMS.sig --url "$(cat shasums-sig-upload.txt)"
      - name: platform endpoint
        run : |
          awk '$2 == "scaffolding_${{ steps.vars.outputs.version }}_darwin_amd64.zip" { print $0 }' scaffolding_${{ steps.vars.outputs.version }}_SHA256SUMS | cut  -d ' ' -f1 > darwin_amd64_hash.txt
          cat darwin_amd64_hash.txt
          awk '$2 == "scaffolding_${{ steps.vars.outputs.version }}_darwin_amd64.zip" { print $0 }' scaffolding_${{ steps.vars.outputs.version }}_SHA256SUMS | cut  -d ' ' -f3 > darwin_amd64_name.txt
          cat darwin_amd64_name.txt
          
      - name: set output hash
        id: get_hash
        run: echo "hash=$(cat darwin_amd64_hash.txt)" >> $GITHUB_OUTPUT
        
      - name: set output name
        id: get_name
        run: echo "name=$(cat darwin_amd64_name.txt)" >> $GITHUB_OUTPUT
          
      - name: get platform
        run : |
          curl \
            --header "Authorization: Bearer $TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            --request POST \
            --data '{
                      "data": {
                        "type": "registry-provider-version-platforms",
                        "attributes": {
                          "os": "darwin",
                          "arch": "amd64",
                          "shasum": "${{ steps.get_hash.outputs.hash }}",
                          "filename": "${{ steps.get_name.outputs.name }}"
                        }
                      }
                    }' \
            https://app.terraform.io/api/v2/organizations/Test-nyx/registry-providers/private/Test-nyx/nyxx/versions/${{ steps.vars.outputs.version }}/platforms > platform.json
      
      - name: show platform json file
        run: cat platform.json
        
      - name: extract binary upload link
        run: jq -r .data.links'."provider-binary-upload"' platform.json > binary_upload.txt
        
      - name : show binary txt
        run : cat binary_upload.txt
        
      - name : upload binary
        run : curl -T ${{ steps.get_name.outputs.name }} --url "$(cat binary_upload.txt)"

          
          

     

 
 

  
