name: get release of provider
on: workflow_dispatch


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Get latest release provider
      uses: rez0n/actions-github-release@main
      id: nyx
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: "hasan-razibul/scaffolding"
        type: "stable"
    - name: echo release number   
      run : echo "${{ steps.nyx.outputs.release_id }}"
        




