name: get release version
on: workflow_dispatch


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Get nyx release version
      uses: rez0n/actions-github-release@main
      id: nyx
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: "hasan-razibul/scaffolding"
        type: "stable"
    - name: echo release number   
      run : echo "${{ steps.nyx.outputs.release }}" | awk 'sub(/^.{1}/,"")' > version.txt
      
    - name: set output
      id: vars
      run: echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT
      
    - name: echo version
      run : echo ${{ steps.vars.outputs.version }}
      

    
      
        




