name: Get Version
on: workflow_dispatch
jobs:
  get-release:
    name: Get the release branch version number
    runs-on: ubuntu-latest

    steps:
    - id: get_version
      uses: battila7/get-version-action@v2

    - run: echo ${{ steps.get_version.outputs.version }}

  
