name: get release version
on: workflow_dispatch


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Get nyx release version
      uses: rez0n/actions-github-release@main
      id: nyx
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: "hasan-razibul/scaffolding"
        type: "stable"
    - name: echo release number   
      id : set-output
      run : echo "${{ steps.nyx.outputs.release }}" | awk 'sub(/^.{1}/,"")' > verison.txt
      
    - name: echo version
      run: cat version.txt
      

    
      
        




