name: get release version
on: workflow_dispatch


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Get nyx release version
      uses: rez0n/actions-github-release@main
      id: nyx
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: "hasan-razibul/scaffolding"
        type: "stable"
    - name: echo release number   
      id : set-output
      run : echo "version= ${{ steps.nyx.outputs.release }}" | awk 'sub(/^.{1}/,"")' >> $GITHUB_OUTPUT
      
    - name: show new output
      run : echo "${{ steps.set-output.outputs.version }}"
    
      
        




