name: Update Payload
on: workflow_dispatch
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get nyx release version
        uses: rez0n/actions-github-release@main
        id: nyx
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "hasan-razibul/scaffolding"
          type: "stable"
      - name: echo release number   
        run : echo "${{ steps.nyx.outputs.release }}" | awk 'sub(/^.{1}/,"")' > version.txt

      - name: set output
        id: vars
        run: echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: echo version
        run : echo ${{ steps.vars.outputs.version }}
        
        
        
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Update payload.json version
        uses: chromee/dot-json-edit-action@v1
        with:
          json_path: ".github/workflows/payload.json"
          field_path: "data/attributes/version"
          field_value: "${{ steps.vars.outputs.version }}"
      - name: after edit
        run: cat .github/workflows/payload.json
        
          
      - name: Curl-1
        run: |
          curl \
            --header "Authorization:Bearer ${{ secrets.TOKEN }}" \
            --header "Content-Type:application/vnd.api+json" \
            --request POST \
            --data @ {
                      "data": {
                        "type": "registry-provider-versions",
                        "attributes": {
                          "version": "${{ steps.vars.outputs.version }}",
                          "key-id": "${{ secrets.KEY_ID }}",
                          "protocols": [
                            "5.0"
                          ]
                        }
                      }
                    }
            https://app.terraform.io/api/v2/organizations/Test-nyx/registry-providers/private/Test-nyx/nyxx/versions

 
 

  
