name: Build and Release

on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    name: checkout code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    - uses: actions/checkout@v3
 
    - name: Gets semantic release info
      id: semantic_release_info
      uses: jossef/action-semantic-release-info@v1
      env:
        GITHUB_TOKEN: ${{ github.token }

    - name: Update payload.json version
      uses: jossef/action-set-json-field@v2.1
      with:
        file: payload.json
        field: version
        value: ${{ steps.semantic_release_info.outputs.git_tag }}
    
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "docs(): bumping release ${{ steps.semantic_release_info.outputs.git_tag }}"
        git tag ${{ steps.semantic_release_info.outputs.git_tag }}
        

