name: Update Payload
on: workflow_dispatch
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release provider
        uses: rez0n/actions-github-release@main
        id: nyx
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "hasan-razibul/scaffolding"
          type: "stable"
      - name: echo release number   
        run : echo "${{ steps.nyx.outputs.release }}"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        
      - name: Update payload.json version
        uses: chromee/dot-json-edit-action@v1
        with:
          json_path: ".github/workflows/payload.json"
          field_path: "data/attributes/version"
          field_value: "${{ steps.nyx.outputs.release }}"
      - name: after edit
        run: cat .github/workflows/payload.json
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: json version update

 
 

  
