name: "Fetch release asset"
on: workflow_dispatch

jobs:
  asset_fetcher:
    runs-on: ubuntu-latest
    steps:
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: 'latest'
        file: "scaffolding_0.2.1_darwin_amd64.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
