name: "Fetch release asset"
on: workflow_dispatch

jobs:
  asset_fetcher:
    runs-on: ubuntu-latest
    steps:
    - uses: wyozi/download-gh-release-asset@master
      with:
        args: release_asset.dat
      env:
        GITHUB_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
