name: "Fetch release asset"
on: workflow_dispatch

jobs:
  asset_fetcher:
    runs-on: ubuntu-latest
    steps:
    - uses: robinraju/release-downloader@v1.7
      with:
        latest: true
        fileName: "*"
        
