name: "Fetch release asset"
on: workflow_dispatch

jobs:
  asset_fetcher:
    runs-on: ubuntu-latest
    steps:
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        file: "*\\.zip"
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
